'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WZ_YOUTUBE_CONVERTER.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;Download button&lt;/title&gt;
        '''    &lt;meta name=&quot;robots&quot; content=&quot;noindex,nofollow&quot;&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css&quot;&gt;
        '''    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/template/css/button.min.css&quot;&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;.
        '''</summary>
        Friend ReadOnly Property p1() As String
            Get
                Return ResourceManager.GetString("p1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;input id=&quot;format&quot; type=&quot;hidden&quot; value=&quot;mp3&quot;&gt;
        '''    &lt;input id=&quot;quality&quot; type=&quot;hidden&quot; value=&quot;192&quot;&gt;
        '''    &lt;input id=&quot;inputstart&quot; type=&quot;checkbox&quot; checked=&quot;checked&quot; value=&quot;-1&quot; style=&quot;display: none&quot;&gt;
        '''    &lt;input id=&quot;inputend&quot; type=&quot;checkbox&quot; checked=&quot;checked&quot; value=&quot;-1&quot; style=&quot;display: none&quot;&gt;
        '''    &lt;div id=&quot;container&quot;&gt;
        '''        &lt;a target=&quot;&quot; href=&quot;&quot; download=&quot;&quot; id=&quot;file&quot; style=&quot;&quot;&gt;
        '''        &lt;button id=&quot;download-audio&quot; style=&quot;background-color:#5F615F;color:#fff&quot;&gt;
        '''            &lt;div&gt; 
        '''                &lt;i id=&quot;icondownlo [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property p2() As String
            Get
                Return ResourceManager.GetString("p2", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
